# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170402_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='active',
        ),
    ]
