# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_urlshort_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
