# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_urlshort_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlShortManager',
            new_name='UrlManager',
        ),
    ]
