# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170402_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlManager',
        ),
    ]
