# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20170403_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='shortcode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
