# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20170403_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.CharField(max_length=255, validators=[shortener.validators.validate_url]),
        ),
    ]
